"""Add payment_done field to Transaction

Revision ID: 3afb2b10fd04
Revises: 
Create Date: 2025-07-09 00:50:14.122073

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3afb2b10fd04'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_done', sa.Boolean(), nullable=True))
        batch_op.alter_column('images',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.alter_column('images',
               existing_type=sa.Text(),
               type_=postgresql.ARRAY(sa.VARCHAR()),
               existing_nullable=True)
        batch_op.drop_column('payment_done')

    # ### end Alembic commands ###
